Repository Software-Projekt-Thiel-2020/Backend, pull requests merged in 2020-06, with the labels that each got.

#49 RESTAPI: Donations
  backend/resources/donations.py
  tests/test_resource_donations.py
Labels: tests missing

#60 added donations smartcontract
  backend/smart_contracts/contracts/Donations.sol
  backend/smart_contracts/contracts/Voucher.sol
  backend/smart_contracts/migrations/3_deploy_contracts.js
  backend/smart_contracts/test/project.js
  backend/smart_contracts/test/voucher.js
Labels: help wanted, tests missing

#101 DB: Attributes of Voucher to VoucherUser
  backend/database/model.py
Labels: important

#98 Added institution get route for voucher
  backend/resources/voucher.py
Labels: important, tests missing
